IMAGE_NAME = "bento/ubuntu-20.04"
N = 2
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
  end
  config.vm.define "kube-master-node" do |master|
    master.vm.box = IMAGE_NAME
    master.vm.network "private_network", ip: "192.168.12.20"
    master.vm.hostname = "kube-master-node"
    master.vm.provision "ansible" do |ansible|
        ansible.playbook = "kubernetes-installation/master-node-ansible-playbook.yml"
        ansible.extra_vars = {
            node_ip: "192.168.12.20",
        }
    end
  end

  (1..N).each do |i|
    config.vm.define "kube-worker-node-#{i}" do |node|
        node.vm.box = IMAGE_NAME
        node.vm.network "private_network", ip: "192.168.12.#{i + 20}"
        node.vm.hostname = "kube-worker-node-#{i}"
        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-installation/worker-node-ansible-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.12.#{i + 20}",
            }
        end
    end
end
end